### ISSUE TITLE
Bitcoin Core should be installed as a package or container

### ISSUE THREAD

**Issue by carnesen** [bitseed-org/bitcoin-box#10]
Currently the btcsetup script simply downloads pre-compiled binaries from bitseed.org into the linaro user's home directory. It'd be better if Bitcoin Core were installed as an apt package from a repository maintained by Bitseed. That would make an upgrade as simple as running "apt-get upgrade bitcoin".

**Comment by jfeldis** [comment]
I agree that would be best.  Do you have any recommendation of a tool that we can use to host a repository that does not require too much overhead to manage?   Any help is this are is appreciated.  Could be project on assembly.com

**Comment by carnesen** [comment]
I'm more familiar with yum/rpm than apt, but I think they're pretty similar. A repo need not be anything more or less than a web server containing the packages and some metadata about them. The tools for creating an apt package are included in the OS. Once the packages are in hand, there's a command for generating the metadata. Then just drop all those files onto the bitseed.org web server. See https://wiki.debian.org/HowToSetupADebianRepository, for example. Indeed, an assembly project might be good for this.

**Comment by carnesen** [comment]
Bitseed might be a good use case for Docker or another Linux container management system.

**Comment by john-light** [comment]
We now install from Bitcoin Core apt repo.
