### ISSUE TITLE
bitcoind shouldn't run as a privileged user

### ISSUE THREAD

**Issue by carnesen** [bitseed-org/bitcoin-box#11]
The Bitseed runs bitcoind as the linaro user who is in the admin group with password-less sudo. It's generally considered a bad idea to run a daemon as a superuser like that.

**Comment by jfeldis** [comment]
What kind of user and privileges do you recommend?   This can be changed in
next version we are planning for summer.

Jay

**Comment by carnesen** [comment]
I'd recommend a "bitcoin" user who has no special privileges except ownership of the bitcoind data directory. That user name is a parameter in the [upstart service specification](https://github.com/bitseed-org/bitcoin-box/issues/8).
