### ISSUE TITLE
Needed:  A simple Web UI Admin Panel

### ISSUE THREAD

**Issue by jfeldis** [bitseed-org/bitcoin-box#3]
A status / control panel accessible via browser from other devices.  Can be PHP, nodejs, etc, as lomg as it does not add more than a few 10's MB of RAM usage

Shows basic node status info:
-indicator:  green: running and syned, yellow: running but not up to date, red - not running
-block height
-version
-block height compared to consensus

Device status:
-RAM use
-CPU load
-available disk space
-dateof last database backup
-device uptime

Device controls
-enable/disable crontab
-start/stop bitcoind
-manual backup/restore
-device safe shutdown

Bitnodes program info
-setup/register device with bitnodes
-register bitcoin address
-report bitnodes stats and ranking for the device

**Comment by jlopp** [comment]
You might want to consider using this dashboard, or at least using it as a baseline for ideas: https://bitbucket.org/mattdoiron/btcndash

You can see a running example at http://87.104.113.2:8334/

**Comment by jfeldis** [comment]
Thanks.  I am also looking at this one

https://github.com/mpatterson99/phpBitAdmin-Bitcoin-HTML5-Wallet

**Comment by john-light** [comment]
New UI located here:

https://github.com/bitseed-org/bitseed-web-ui-2
