### ISSUE TITLE
Smarter Disk Use Management

### ISSUE THREAD

**Issue by jlopp** [bitseed-org/bitcoin-box#4]
Trying to be forward-thinking here:

I think it would be a good idea for the backup script to check the disk usage before shutting down bitcoind and running a backup. If the disk usage is > ~45% then it shouldn't make a backup, and it should also delete the block, chainstate, and database directories to free up space.

In future versions of Bitcoin Core you could instead enable pruning on the node rather than disable the backups, but that is TBD. The current state of pruning actually results in a node no longer operating as a full node and accepting incoming connections, because there is no way for a node to broadcast that it only hosts a certain part of the blockchain.

**Comment by jfeldis** [comment]
My thinking is that we may have other solutions before we run out of space.   It may be 2-3 years before this is an issue. These are options:
1) Pruning could allow the device to prune when the disk limits are reached, as you mentioned.   It would still be keeping 50GB+ of blockchain.   This would require an update of the binaries to the next version.  
2) We could delete the backup as you suggest.  I am not sure how common database corruption will be in the wild (I have seen it occasionally in testing), but without a backup, a 50GB+ blockchain could take 2 weeks to re-index...  power outages and pulling-the-plug are the typical culprits
3) The disk capacity sweet spot continues to rise, so we may be looking st 250GB at the same price fairly soon.
4) We are working on a small battery backup circuit that could keep the device going for a few minutes after a sudden power loss, and allow it to execute a proper shutdown.

It wont hurt to check disk space and script the fall-back mode you suggest.

**Comment by jfeldis** [comment]
We now have a rudimentary status panel in PHP.   This could expanded to help monitor disk space and such, and to let the use change some settings.

The admin panel can be added to devices s/n <31.  
The script is linked.  Look in the comments for instructions  (need to add dependencies and change rpc password to allow php to read it.)
https://github.com/BitSeed-org/bitcoin-box/blob/master/setup/admin-panel-install.sh
