### ISSUE TITLE
Deploy bitcoind as upstart service

### ISSUE THREAD

**Issue by carnesen** [bitseed-org/bitcoin-box#8]
I gather from poking around this repository (mine is en route) that the Bitseed has a cron job that restarts bitcoind when it crashes. Upstart, the default init system on Ubuntu 14.04 (the Bitseed OS), is better at that and should be used instead of cron. See here https://bitcointalk.org/index.php?topic=25518.0 for a sample bitcoind upstart configuration file.

**Comment by jfeldis** [comment]
Part of the reason I did not do this, is that at this stage, debugging is easier when the bitcoind startup is initiated manually. RAM and CPU load from bitcoind is much heavier at at startup than during ongoing operation, so it may be best to wait until system startup us fully complete.  Perhaps upstart can run a startup script with a ~5 min delay.  This could also allow a user to abort the bitcoind startup if necessary
